-- Generates the reference tables under docs/_generated/ plus the native
-- :help file (doc/nvim-config.txt) from the SAME registries the running
-- config uses (util.keymap_registry, util.command_registry,
-- languages.registry, tools.registry, scripts/plugins.tsv). This is the
-- single generator that keeps the Sphinx pages (which {include} these
-- partials), the native :help, and :NvimKeymaps/:NvimCommands from
-- drifting apart.
--
-- Output goes to docs/_generated/ rather than the repository root so all
-- documentation lives under docs/ -- and the results are COMMITTED, not
-- gitignored, because Read the Docs builds this site without Neovim
-- available and so can never run this generator itself.
--
-- Run via: nvim --headless -u init.lua -l scripts/generate-docs.lua
-- (also wrapped by scripts/docs-build.sh, which runs this before Sphinx.)
local repo_root = vim.fn.getcwd()
local generated_dir = repo_root .. "/docs/_generated"

vim.fn.mkdir(generated_dir, "p")

local function write(path, lines)
  local f = assert(io.open(path, "w"))
  f:write(table.concat(lines, "\n"))
  f:write("\n")
  f:close()
  print("wrote " .. path)
end

local GENERATED_HEADER =
  "<!-- GENERATED by scripts/generate-docs.lua -- do not edit by hand, edit the registry instead. -->"

-- docs/_generated/keymaps.md ------------------------------------------------
local function gen_keymaps()
  local km = require("util.keymap_registry")
  local lines = { GENERATED_HEADER, "", "# Keymaps", "", "`<leader>` is `<space>`, `<localleader>` is `\\`.", "" }
  lines[#lines + 1] = "| Mode | Key | Action | Group | Context |"
  lines[#lines + 1] = "|---|---|---|---|---|"
  for _, k in ipairs(km.all()) do
    local mode = type(k.mode) == "table" and table.concat(k.mode, ",") or k.mode
    lines[#lines + 1] = string.format("| `%s` | `%s` | %s | %s | %s |", mode, k.lhs, k.desc, k.group, k.context)
  end
  write(generated_dir .. "/keymaps.md", lines)
  return km.all()
end

-- docs/_generated/commands.md -----------------------------------------------
local function gen_commands()
  local cmdreg = require("util.command_registry")
  local lines = { GENERATED_HEADER, "", "# Commands", "" }
  local last_category = nil
  for _, c in ipairs(cmdreg.all()) do
    if c.category ~= last_category then
      lines[#lines + 1] = "## " .. c.category
      lines[#lines + 1] = ""
      last_category = c.category
    end
    local head = ":" .. c.name .. (c.args and (" " .. c.args) or "")
    lines[#lines + 1] = "### `" .. head .. "`"
    lines[#lines + 1] = ""
    lines[#lines + 1] = c.desc
    if c.example then
      lines[#lines + 1] = ""
      lines[#lines + 1] = "```vim"
      lines[#lines + 1] = c.example
      lines[#lines + 1] = "```"
    end
    lines[#lines + 1] = ""
  end
  write(generated_dir .. "/commands.md", lines)
  return cmdreg.all()
end

-- docs/_generated/tools.md --------------------------------------------------
local function gen_tools()
  local tools = require("tools.registry")
  local CATEGORY_LABEL =
    { lsp = "Language Servers", formatter = "Formatters", linter = "Linters", debugger = "Debuggers" }
  local lines = {
    GENERATED_HEADER,
    "",
    "# Tools",
    "",
    "Status for your machine: run `:ToolsStatus` or `:NvimConfigHealth` inside Neovim.",
    "",
  }
  for _, category in ipairs({ "lsp", "formatter", "linter", "debugger" }) do
    lines[#lines + 1] = "## " .. CATEGORY_LABEL[category]
    lines[#lines + 1] = ""
    lines[#lines + 1] = "| Tool | Mason package | Profiles | Notes |"
    lines[#lines + 1] = "|---|---|---|---|"
    for _, t in ipairs(tools.all()) do
      if t.category == category then
        lines[#lines + 1] = string.format(
          "| %s | %s | %s | %s |",
          t.name,
          t.mason and ("`" .. t.mason .. "`") or "_(manual install)_",
          table.concat(t.profiles, ", "),
          t.note or ""
        )
      end
    end
    lines[#lines + 1] = ""
  end
  write(generated_dir .. "/tools.md", lines)
end

-- docs/_generated/languages.md ----------------------------------------------
local function gen_languages()
  local languages = require("languages.registry")
  local tools = require("tools.registry")

  local function tool_name(id)
    if not id then
      return nil
    end
    local t = tools.get(id)
    return t and t.name or id
  end

  local lines = { GENERATED_HEADER, "", "# Supported Languages", "" }
  for _, lang in ipairs(languages.all()) do
    lines[#lines + 1] = "## " .. lang.id
    lines[#lines + 1] = ""
    lines[#lines + 1] = "- **Filetypes:** " .. table.concat(lang.filetypes, ", ")
    if lang.extensions then
      lines[#lines + 1] = "- **Extensions:** " .. table.concat(lang.extensions, ", ")
    end
    if lang.treesitter then
      lines[#lines + 1] = "- **Tree-sitter:** " .. table.concat(lang.treesitter, ", ")
    end
    if lang.root_markers then
      lines[#lines + 1] = "- **Project root markers:** " .. table.concat(lang.root_markers, ", ")
    end
    lines[#lines + 1] = "- **LSP:** " .. (lang.lsp and tool_name(lang.lsp.tool) or "_none_")
    if lang.formatters and #lang.formatters > 0 then
      local names = {}
      for _, id in ipairs(lang.formatters) do
        table.insert(names, tool_name(id))
      end
      lines[#lines + 1] = "- **Formatters:** " .. table.concat(names, ", ")
    else
      lines[#lines + 1] = "- **Formatters:** _none_"
    end
    if lang.linters and #lang.linters > 0 then
      local names = {}
      for _, id in ipairs(lang.linters) do
        table.insert(names, tool_name(id))
      end
      lines[#lines + 1] = "- **Linters:** " .. table.concat(names, ", ")
    else
      lines[#lines + 1] = "- **Linters:** _none_"
    end
    lines[#lines + 1] = "- **Debugger:** " .. (lang.debugger and tool_name(lang.debugger.tool) or "_none_")
    if lang.notes then
      lines[#lines + 1] = "- **Notes:** " .. lang.notes
    end
    lines[#lines + 1] = ""
  end
  write(generated_dir .. "/languages.md", lines)
end

-- docs/_generated/plugins.md ------------------------------------------------
local function gen_plugins()
  local lines = {
    GENERATED_HEADER,
    "",
    "# Plugins",
    "",
    "All plugins are vendored in-repo via `git subtree` (see `scripts/plugins.tsv` / `plugins.lock`); nothing is downloaded at Neovim startup.",
    "",
  }
  local sections = {
    { key = "start", title = "Always loaded (`pack/vendor/start/`)" },
    { key = "opt", title = "Loaded on demand (`pack/vendor/opt/`)" },
  }
  local f = assert(io.open(repo_root .. "/scripts/plugins.tsv", "r"))
  local rows = {}
  local first = true
  for line in f:lines() do
    if first then
      first = false
    else
      local cols = {}
      for col in (line .. "\t"):gmatch("(.-)\t") do
        table.insert(cols, col)
      end
      table.insert(
        rows,
        { name = cols[1], url = cols[2], branch = cols[3], prefix = cols[4], load_type = cols[5], trigger = cols[6] }
      )
    end
  end
  f:close()

  for _, section in ipairs(sections) do
    lines[#lines + 1] = "## " .. section.title
    lines[#lines + 1] = ""
    lines[#lines + 1] = "| Plugin | Upstream | Trigger |"
    lines[#lines + 1] = "|---|---|---|"
    for _, r in ipairs(rows) do
      if r.load_type == section.key then
        lines[#lines + 1] = string.format("| %s | %s | %s |", r.name, r.url:gsub("%.git$", ""), r.trigger)
      end
    end
    lines[#lines + 1] = ""
  end
  write(generated_dir .. "/plugins.md", lines)
end

-- docs/_generated/third-party-licenses.md -------------------------------------
-- Inventory of the licenses of every vendored plugin, read from the LICENSE
-- file each one ships. Generated rather than hand-maintained so it cannot
-- silently go stale when a plugin is added, removed or relicensed upstream --
-- the same reason every other table here is generated. See LICENSE at the
-- repo root for how these relate to this config's own MIT license.
local function gen_third_party_licenses()
  -- Matched against the first ~40 lines of each LICENSE file, most specific
  -- first (e.g. "GNU LESSER" must beat "GNU GENERAL PUBLIC").
  local PATTERNS = {
    { pattern = "GNU LESSER GENERAL PUBLIC LICENSE", name = "LGPL" },
    { pattern = "GNU GENERAL PUBLIC LICENSE", name = "GPL" },
    { pattern = "GNU General Public License", name = "GPL" },
    { pattern = "Apache License", name = "Apache-2.0" },
    { pattern = "MIT License", name = "MIT" },
    { pattern = "Permission is hereby granted, free of charge", name = "MIT" },
    { pattern = "BSD", name = "BSD" },
    { pattern = "Unlicense", name = "Unlicense" },
  }

  local function detect(dir)
    for _, candidate in ipairs({ "LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE", "LICENCE.md", "COPYING" }) do
      local path = dir .. "/" .. candidate
      local fh = io.open(path, "r")
      if fh then
        local head = fh:read(4000) or ""
        fh:close()
        local label
        for _, p in ipairs(PATTERNS) do
          if head:find(p.pattern, 1, true) then
            label = p.name
            break
          end
        end
        -- GPL/LGPL: report the actual version, it matters. Two spellings in
        -- the wild -- the verbatim GPL text header ("Version 3, 29 June
        -- 2007") and the short "either version 3 of the License" preamble
        -- projects paste into their own LICENSE (e.g. nvim-tree.lua).
        if label == "GPL" or label == "LGPL" then
          local version = head:match("Version (%d)") or head:match("version (%d) of the License")
          if version then
            label = label .. "-" .. version .. ".0"
          end
        end
        return label or "see file", candidate
      end
    end
    return nil, nil
  end

  local lines = {
    GENERATED_HEADER,
    "",
    "# Third-Party Licenses",
    "",
    "Every plugin under `pack/vendor/` is redistributed unmodified under its",
    "own license, listed below and detected from the LICENSE file each plugin",
    "ships. The authoritative text is always that file inside the plugin's own",
    "directory; this table is a convenience index.",
    "",
    "This configuration's own code is MIT (see `LICENSE` at the repository",
    "root), which does **not** extend to these plugins.",
    "",
    "| Plugin | License | License file |",
    "|---|---|---|",
  }

  local names = {}
  for _, base in ipairs({ "start", "opt" }) do
    local dir = repo_root .. "/pack/vendor/" .. base
    for name, kind in vim.fs.dir(dir) do
      if kind == "directory" then
        table.insert(names, { name = name, dir = dir .. "/" .. name })
      end
    end
  end
  table.sort(names, function(a, b)
    return a.name:lower() < b.name:lower()
  end)

  for _, entry in ipairs(names) do
    local label, file = detect(entry.dir)
    lines[#lines + 1] = string.format(
      "| %s | %s | %s |",
      entry.name,
      label or "**none found**",
      file and ("`" .. file .. "`") or "_(no license file in the plugin)_"
    )
  end
  lines[#lines + 1] = ""

  write(generated_dir .. "/third-party-licenses.md", lines)
end

-- doc/nvim-config.txt (native :help) ---------------------------------------
local function vimdoc_escape(s)
  return (s:gsub("|", "\\|"))
end

local function gen_help(keymaps)
  local cmdreg = require("util.command_registry")
  local languages = require("languages.registry")
  local tools = require("tools.registry")

  local W = 78
  local function tag(name)
    local t = "*" .. name .. "*"
    return string.rep(" ", math.max(1, W - #t)) .. t
  end
  local function section(title, tagname)
    return {
      "==============================================================================",
      title .. tag(tagname),
      "",
    }
  end

  local lines = {}
  vim.list_extend(lines, {
    "*nvim-config.txt*  A hand-written, fully offline-capable Neovim configuration",
    "",
    tag("nvim-config"),
    "",
    "Author: generated from this repository's registries -- see :NvimDocs for the",
    "full local Sphinx documentation, and README.md for a human-written overview.",
    "",
    "==============================================================================",
    "CONTENTS" .. tag("nvim-config-contents"),
    "",
    "  1. Overview .......................... |nvim-config-overview|",
    "  2. Commands .......................... |nvim-config-commands|",
    "  3. Keymaps ........................... |nvim-config-keymaps|",
    "  4. Languages .......................... |nvim-config-languages|",
    "  5. Tools .............................. |nvim-config-tools|",
    "",
  })

  vim.list_extend(lines, section("1. OVERVIEW", "nvim-config-overview"))
  vim.list_extend(lines, {
    "A from-scratch, fully documented Neovim configuration. No plugin manager",
    "downloads anything at startup; all plugins are vendored in pack/vendor/ via",
    "git subtree. See |nvim-config-offline| in the Sphinx docs (./scripts/docs-build.sh)",
    "for the full offline-usage explanation, and :NvimConfigHealth for a live report",
    "of what's installed on this machine.",
    "",
  })

  vim.list_extend(lines, section("2. COMMANDS", "nvim-config-commands"))
  for _, c in ipairs(cmdreg.all()) do
    local head = ":" .. c.name .. (c.args and (" " .. c.args) or "")
    lines[#lines + 1] = head .. tag("nvim-config-cmd-" .. c.name:lower())
    lines[#lines + 1] = "    " .. vimdoc_escape(c.desc)
    lines[#lines + 1] = ""
  end

  vim.list_extend(lines, section("3. KEYMAPS", "nvim-config-keymaps"))
  local last_group = nil
  for _, k in ipairs(keymaps) do
    if k.group ~= last_group then
      lines[#lines + 1] = k.group .. " ~"
      lines[#lines + 1] = ""
      last_group = k.group
    end
    local mode = type(k.mode) == "table" and table.concat(k.mode, ",") or k.mode
    lines[#lines + 1] = string.format("    %-6s %-18s %s", mode, k.lhs, vimdoc_escape(k.desc))
  end
  lines[#lines + 1] = ""

  vim.list_extend(lines, section("4. LANGUAGES", "nvim-config-languages"))
  for _, lang in ipairs(languages.all()) do
    lines[#lines + 1] = lang.id .. tag("nvim-config-lang-" .. lang.id)
    lines[#lines + 1] = "    Filetypes: " .. table.concat(lang.filetypes, ", ")
    lines[#lines + 1] = "    LSP: " .. (lang.lsp and lang.lsp.tool or "none")
    lines[#lines + 1] = ""
  end

  vim.list_extend(lines, section("5. TOOLS", "nvim-config-tools"))
  lines[#lines + 1] = "See docs/_generated/tools.md or :ToolsStatus for the full, current table (kept out of this"
  lines[#lines + 1] = "file to avoid a fourth copy of the same data)."
  lines[#lines + 1] = ""
  lines[#lines + 1] = "vim:tw=78:ts=8:noet:ft=help:norl:"

  vim.fn.mkdir(repo_root .. "/doc", "p")
  write(repo_root .. "/doc/nvim-config.txt", lines)
  _ = tools
end

local keymaps = gen_keymaps()
gen_commands()
gen_tools()
gen_languages()
gen_plugins()
gen_third_party_licenses()
gen_help(keymaps)

print("==> Docs generated. Run :helptags doc (or scripts/install.sh) to refresh help tags.")
os.exit(0)
